In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder


In [2]:
data=pd.read_csv("datasets\\final_dataset_new8.csv")
dataT=pd.read_csv("datasets\\test_new8.csv")
data.head()
dataT.head()

Date     HomeTeam       AwayTeam FTR   VCH  B365H  HTGS  ATGS  HTGC  \
0  2023-08-11      Burnley       Man City  NH  9.50   8.00   0.0   0.0   0.0   
1  2023-08-12      Arsenal  Nott'm Forest   H  1.14   1.18   0.0   0.0   0.0   
2  2023-08-12  Bournemouth       West Ham  NH  2.63   2.70   0.0   0.0   0.0   
3  2023-08-12     Brighton          Luton   H  1.29   1.33   0.0   0.0   0.0   
4  2023-08-12      Everton         Fulham  NH  2.20   2.20   0.0   0.0   0.0   

   ATGC  ...  HTGD  ATGD DiffPts DiffFormPts DiffLP H2HM1 H2HM2 H2HM3 H2HM4  \
0   0.0  ...   0.0   0.0     0.0         0.0   17.0     1     0     1     0   
1   0.0  ...   0.0   0.0     0.0         0.0  -14.0     0     2    -1    -1   
2   0.0  ...   0.0   0.0     0.0         0.0    1.0     1     0     0     1   
3   0.0  ...   0.0   0.0     0.0         0.0  -12.0    -1    -1    -1    -1   
4   0.0  ...   0.0   0.0     0.0         0.0    7.0     1     1     1     1   

  H2HM5  
0     0  
1    -1  
2     2  
3    -1  
4     0  

[5 rows x 40 columns]

In [3]:
ftrLE=LabelEncoder()
data.FTR=ftrLE.fit_transform(data.FTR)
dataT.FTR=ftrLE.transform(dataT.FTR)
dataT.head()

Date     HomeTeam       AwayTeam  FTR   VCH  B365H  HTGS  ATGS  HTGC  \
0  2023-08-11      Burnley       Man City    1  9.50   8.00   0.0   0.0   0.0   
1  2023-08-12      Arsenal  Nott'm Forest    0  1.14   1.18   0.0   0.0   0.0   
2  2023-08-12  Bournemouth       West Ham    1  2.63   2.70   0.0   0.0   0.0   
3  2023-08-12     Brighton          Luton    0  1.29   1.33   0.0   0.0   0.0   
4  2023-08-12      Everton         Fulham    1  2.20   2.20   0.0   0.0   0.0   

   ATGC  ...  HTGD  ATGD DiffPts DiffFormPts DiffLP H2HM1 H2HM2 H2HM3 H2HM4  \
0   0.0  ...   0.0   0.0     0.0         0.0   17.0     1     0     1     0   
1   0.0  ...   0.0   0.0     0.0         0.0  -14.0     0     2    -1    -1   
2   0.0  ...   0.0   0.0     0.0         0.0    1.0     1     0     0     1   
3   0.0  ...   0.0   0.0     0.0         0.0  -12.0    -1    -1    -1    -1   
4   0.0  ...   0.0   0.0     0.0         0.0    7.0     1     1     1     1   

  H2HM5  
0     0  
1    -1  
2     2  
3    -1  
4     0  

[5 rows x 40 columns]

In [4]:
hmLE=LabelEncoder()
data.HM1=hmLE.fit_transform(data.HM1)
dataT.HM1=hmLE.fit_transform(dataT.HM1)
dataT.head()

Date     HomeTeam       AwayTeam  FTR   VCH  B365H  HTGS  ATGS  HTGC  \
0  2023-08-11      Burnley       Man City    1  9.50   8.00   0.0   0.0   0.0   
1  2023-08-12      Arsenal  Nott'm Forest    0  1.14   1.18   0.0   0.0   0.0   
2  2023-08-12  Bournemouth       West Ham    1  2.63   2.70   0.0   0.0   0.0   
3  2023-08-12     Brighton          Luton    0  1.29   1.33   0.0   0.0   0.0   
4  2023-08-12      Everton         Fulham    1  2.20   2.20   0.0   0.0   0.0   

   ATGC  ...  HTGD  ATGD  DiffPts DiffFormPts DiffLP H2HM1 H2HM2 H2HM3 H2HM4  \
0   0.0  ...   0.0   0.0      0.0         0.0   17.0     1     0     1     0   
1   0.0  ...   0.0   0.0      0.0         0.0  -14.0     0     2    -1    -1   
2   0.0  ...   0.0   0.0      0.0         0.0    1.0     1     0     0     1   
3   0.0  ...   0.0   0.0      0.0         0.0  -12.0    -1    -1    -1    -1   
4   0.0  ...   0.0   0.0      0.0         0.0    7.0     1     1     1     1   

  H2HM5  
0     0  
1    -1  
2     2  
3    -1  
4     0  

[5 rows x 40 columns]

In [5]:
data.HM2=hmLE.fit_transform(data.HM2)
data.HM3=hmLE.fit_transform(data.HM3)
data.HM4=hmLE.fit_transform(data.HM4)
data.HM5=hmLE.fit_transform(data.HM5)
data.AM1=hmLE.fit_transform(data.AM1)
data.AM2=hmLE.fit_transform(data.AM2)
data.AM3=hmLE.fit_transform(data.AM3)
data.AM4=hmLE.fit_transform(data.AM4)
data.AM5=hmLE.fit_transform(data.AM5)

dataT.HM2=hmLE.fit_transform(dataT.HM2)
dataT.HM3=hmLE.fit_transform(dataT.HM3)
dataT.HM4=hmLE.fit_transform(dataT.HM4)
dataT.HM5=hmLE.fit_transform(dataT.HM5)
dataT.AM1=hmLE.fit_transform(dataT.AM1)
dataT.AM2=hmLE.fit_transform(dataT.AM2)
dataT.AM3=hmLE.fit_transform(dataT.AM3)
dataT.AM4=hmLE.fit_transform(dataT.AM4)
dataT.AM5=hmLE.fit_transform(dataT.AM5)

In [6]:
data.head()

Date     HomeTeam    AwayTeam  FTR   VCH  B365H  HTGS  ATGS  HTGC  \
0  2010-08-14  Aston Villa    West Ham    0  2.00   2.00   0.0   0.0   0.0   
1  2010-08-14    Blackburn     Everton    0  3.10   2.88   0.0   0.0   0.0   
2  2010-08-14       Bolton      Fulham    1  2.20   2.20   0.0   0.0   0.0   
3  2010-08-14      Chelsea   West Brom    0  1.17   1.17   0.0   0.0   0.0   
4  2010-08-14   Sunderland  Birmingham    1  2.20   2.10   0.0   0.0   0.0   

   ATGC  ...  HTGD  ATGD  DiffPts  DiffFormPts  DiffLP  H2HM1  H2HM2  H2HM3  \
0   0.0  ...   0.0   0.0      0.0          0.0   -11.0     -1     -1     -1   
1   0.0  ...   0.0   0.0      0.0          0.0     2.0     -1     -1     -1   
2   0.0  ...   0.0   0.0      0.0          0.0     2.0     -1     -1     -1   
3   0.0  ...   0.0   0.0      0.0          0.0   -17.0     -1     -1     -1   
4   0.0  ...   0.0   0.0      0.0          0.0     4.0     -1     -1     -1   

   H2HM4  H2HM5  
0     -1     -1  
1     -1     -1  
2     -1     -1  
3     -1     -1  
4     -1     -1  

[5 rows x 40 columns]

In [7]:
print(data.shape)
print(dataT.shape)

(4940, 40)
(380, 40)


In [8]:
onehotencoder=OneHotEncoder()
onehotencoder.fit(data.FTR.values.reshape(-1,1))

OneHotEncoder()

In [9]:
final=onehotencoder.transform([[each] for each in data.FTR]).toarray()

In [10]:
final.shape
print(final)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]


In [11]:
finalT=onehotencoder.transform([[each] for each in dataT.FTR]).toarray()

In [12]:
finalT.shape

(380, 2)

In [13]:
data.loc[:,"final1"]=final[:,0]
data.loc[:,"final2"]=final[:,1]
# data.loc[:,"final3"]=final[:,2]
print(final[:,0])
print(final[:,1])
print(data)

[1. 1. 0. ... 1. 1. 0.]
[0. 0. 1. ... 0. 0. 1.]
            Date     HomeTeam     AwayTeam  FTR   VCH  B365H      HTGS  \
0     2010-08-14  Aston Villa     West Ham    0  2.00   2.00  0.000000   
1     2010-08-14    Blackburn      Everton    0  3.10   2.88  0.000000   
2     2010-08-14       Bolton       Fulham    1  2.20   2.20  0.000000   
3     2010-08-14      Chelsea    West Brom    0  1.17   1.17  0.000000   
4     2010-08-14   Sunderland   Birmingham    1  2.20   2.10  0.000000   
...          ...          ...          ...  ...   ...    ...       ...   
4935  2023-05-28      Everton  Bournemouth    0  1.44   1.50  0.323529   
4936  2023-05-28        Leeds    Tottenham    1  2.75   2.75  0.460784   
4937  2023-05-28    Leicester     West Ham    0  1.90   1.91  0.480392   
4938  2023-05-28   Man United       Fulham    0  1.50   1.50  0.549020   
4939  2023-05-28  Southampton    Liverpool    1  7.00   6.50  0.313725   

          ATGS      HTGC      ATGC  ...   DiffPts  DiffFormPts 

In [14]:
# data=data.drop(["final"],axis=1)
data.head()

Date     HomeTeam    AwayTeam  FTR   VCH  B365H  HTGS  ATGS  HTGC  \
0  2010-08-14  Aston Villa    West Ham    0  2.00   2.00   0.0   0.0   0.0   
1  2010-08-14    Blackburn     Everton    0  3.10   2.88   0.0   0.0   0.0   
2  2010-08-14       Bolton      Fulham    1  2.20   2.20   0.0   0.0   0.0   
3  2010-08-14      Chelsea   West Brom    0  1.17   1.17   0.0   0.0   0.0   
4  2010-08-14   Sunderland  Birmingham    1  2.20   2.10   0.0   0.0   0.0   

   ATGC  ...  DiffPts  DiffFormPts  DiffLP  H2HM1  H2HM2  H2HM3  H2HM4  H2HM5  \
0   0.0  ...      0.0          0.0   -11.0     -1     -1     -1     -1     -1   
1   0.0  ...      0.0          0.0     2.0     -1     -1     -1     -1     -1   
2   0.0  ...      0.0          0.0     2.0     -1     -1     -1     -1     -1   
3   0.0  ...      0.0          0.0   -17.0     -1     -1     -1     -1     -1   
4   0.0  ...      0.0          0.0     4.0     -1     -1     -1     -1     -1   

   final1  final2  
0     1.0     0.0  
1     1.0     0.0  
2     0.0     1.0  
3     1.0     0.0  
4     0.0     1.0  

[5 rows x 42 columns]

In [15]:
dataT.loc[:,"final1"]=finalT[:,0]
dataT.loc[:,"final2"]=finalT[:,1]
# dataT.loc[:,"final3"]=finalT[:,2]

In [16]:
# data=data.drop(["final"],axis=1)
dataT.head()

Date     HomeTeam       AwayTeam  FTR   VCH  B365H  HTGS  ATGS  HTGC  \
0  2023-08-11      Burnley       Man City    1  9.50   8.00   0.0   0.0   0.0   
1  2023-08-12      Arsenal  Nott'm Forest    0  1.14   1.18   0.0   0.0   0.0   
2  2023-08-12  Bournemouth       West Ham    1  2.63   2.70   0.0   0.0   0.0   
3  2023-08-12     Brighton          Luton    0  1.29   1.33   0.0   0.0   0.0   
4  2023-08-12      Everton         Fulham    1  2.20   2.20   0.0   0.0   0.0   

   ATGC  ...  DiffPts  DiffFormPts  DiffLP  H2HM1  H2HM2  H2HM3  H2HM4  H2HM5  \
0   0.0  ...      0.0          0.0    17.0      1      0      1      0      0   
1   0.0  ...      0.0          0.0   -14.0      0      2     -1     -1     -1   
2   0.0  ...      0.0          0.0     1.0      1      0      0      1      2   
3   0.0  ...      0.0          0.0   -12.0     -1     -1     -1     -1     -1   
4   0.0  ...      0.0          0.0     7.0      1      1      1      1      0   

   final1  final2  
0     0.0     1.0  
1     1.0     0.0  
2     0.0     1.0  
3     1.0     0.0  
4     0.0     1.0  

[5 rows x 42 columns]

In [17]:
# dataT[["final1","final2","final3"]].values.shape
dataT[["final1","final2"]].values.shape

(380, 2)

In [18]:
data=data.drop(["HM5","AM5"],axis=1)
dataT=dataT.drop(["HM5","AM5"],axis=1)

In [19]:
print(data.shape)
print(dataT.shape)

(4940, 40)
(380, 40)


In [20]:
data.to_csv("allAtt_onehot_large_train_new8.csv",index=None)
dataT.to_csv("allAtt_onehot_large_test_new8.csv",index=None)
